version: 2
jobs:
  build:
    docker:
      - image: cmssw/cmssw:CMSSW_9_3_2
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
